framework:
    messenger:
        # Si un message échoue, il sera envoyé vers ce transport
        failure_transport: failed

        transports:
            # Utilisation du transport synchrone, ce qui envoie immédiatement les messages
            sync: 'sync://'

            # Transport pour les messages échoués
            failed: 'doctrine://default?queue_name=failed'

        # Configuration des buses de messages
        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []

        routing:
            # Acheminer les messages de type SendEmailMessage vers le transport synchrone
            Symfony\Component\Mailer\Messenger\SendEmailMessage: sync

            # Autres messages peuvent être acheminés de la même manière si nécessaire
            Symfony\Component\Notifier\Message\ChatMessage: sync
            Symfony\Component\Notifier\Message\SmsMessage: sync

            # Si tu as d'autres messages personnalisés à acheminer, tu peux les ajouter
            # 'App\Message\YourMessage': sync
