vich_uploader:
  db_driver: orm
  metadata:
    type: attribute
  mappings:
    Stage:
      uri_prefix: /images/stage
      upload_destination: "%kernel.project_dir%/public/images/stage"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    CompteRendu:
      uri_prefix: /images/compteRendu
      upload_destination: "%kernel.project_dir%/public/images/compteRendu"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
