vich_uploader:
  db_driver: orm
  metadata:
    type: attribute
  mappings:
    Stage:
      uri_prefix: /images/stage
      upload_destination: "%kernel.project_dir%/public/images/stage"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    compte_rendu_image:
      uri_prefix: /images/compteRendu
      upload_destination: '%kernel.project_dir%/public/images/compteRendu'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      delete_on_update: true
      delete_on_remove: true
