# The name of this app. Must be unique within a project.
name: app

# The runtime the application uses.
type: "php:8.3"

# Defines how the application is built and deployed.
build:
  flavor: "composer"

# Storage for the application
disk: 512

# Services used by the application
dependencies:
  php:
    - ext-pdo
    - ext-mysqli

mounts:
  "/var": { source: "var", source_path: "var" }

# Web server settings
web:
  locations:
    "/":
      root: "public"
      passthru: "/index.php"

services:
  mysql: "mysql:8.0"
