name: app

type: php:8.3

mounts:
  '/var/www/html':
    source: 'local'
    source_path: 'html'

dependencies:
  php:
    - ext-pdo
    - ext-mysqli

disk:
  size: 256

routes:
  "https://www.{default}/":
    type: upstream
    upstream: "app:http"
  "https://{default}/":
    type: redirect
    to: "https://www.{default}/"
