# The name of this app. Must be unique within a project.
name: app

# The runtime the application uses.  
type: "php:8.3"

# Defines how the application is built and deployed.
build:
  flavor: "composer"

# Storage for the application
disk: 512

# Web server settings
web:
  locations:
    "/":
      root: "public"
      passthru: "/index.php"

# Dependencies for PHP extensions (correct format)
dependencies:
  php:
    ext-pdo: true
    ext-mysqli: true

# No need to declare MySQL here, Platform.sh does it automatically.
